name: doc_text_extractor
description: A Flutter package for extracting text and chapters from Word (.doc, .docx), PDF, Google Docs URLs, and Markdown (.md) files, with offline .doc and .md support and real filename extraction.
version: 2.1.0
homepage: https://github.com/Destiny-Ed/doc_text_extractor
repository: https://github.com/Destiny-Ed/doc_text_extractor

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  syncfusion_flutter_pdf: ^31.2.15
  archive: ^4.0.7
  xml: ^6.6.1
  markdown: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
